name: Release

on:
  push:
    tags:
    - '*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.24"

    - name: Patch aristanetworks/goeapi dependency
      run: |
        go mod vendor
        sed -i 's/\(Version[[:space:]]*\)int/\1string/' ./vendor/github.com/aristanetworks/goeapi/eapi.go
        sed -i 's/p := Parameters{1, commands, encoding}/p := Parameters{"latest", commands, encoding}/' ./vendor/github.com/aristanetworks/goeapi/eapilib.go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
